#!/bin/bash
url=""
prev=""
for arg in "$@"; do
  if [[ $arg == https://* && $prev != "-e" && -z $url ]]; then url="$arg"; fi
  prev="$arg"
done

emit() { printf '%s %s' "$1" "${FAKE_CODE:-200}"; }

[[ -n ${FAKE_URL_LOG:-} ]] && printf '%s\n' "$url" >>"$FAKE_URL_LOG"

[[ -n ${FAKE_CURL_FAIL:-} ]] && exit 7

[[ -n ${FAKE_CLOUDFLARE:-} ]] && emit "<html><title>Just a moment...</title></html>" && exit 0

case "$url" in
*/search*) emit "$(cat "$FIXTURES/search.html")" ;;
*/episode/list/*) emit "$(cat "$FIXTURES/episodes.json")" ;;
*/episode/servers*) emit "$(cat "${FAKE_SERVERS:-$FIXTURES/servers-vidstream.html}")" ;;
*/stream/getSources*) emit "$(cat "${FAKE_SOURCES:-$FIXTURES/sources-cdn.json}")" ;;
*megaplay*) emit "$(cat "${FAKE_EMBED_PAGE:-$FIXTURES/embed-megaplay.html}")" ;;
*master.m3u8*) emit "$(cat "${FAKE_MASTER:-$FIXTURES/master.m3u8}")" ;;
*) emit "" ;;
esac
